name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: read
  security-events: write  # required for uploading SARIF reports

jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # - name: Terraform Format (non-blocking)
      #   run: terraform fmt -check -recursive || echo "Formatting issues detected, but continuing..."
        

      # - name: Terraform Validate
      #   run: terraform validate

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --init && tflint

      # - name: Install Checkov
      #   run: pip install checkov

      # - name: Run Checkov
      #   run: checkov -d . --output sarif --output-file checkov.sarif

      # - name: Upload Checkov SARIF
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: checkov.sarif
